FROM almalinux:8
LABEL AUTHOR="Aadarsh" \
      INSTRUCTION="Label" \
      OS="Almalinux" 

## \ Slash should be given if are specifing mutliple LABELS
## LABEL Instrction adds extra metadata to an image.
## We can filter the image by using the lables.
## Build the image and run this command: docker images --filter label=AUTHOR=Aadarsh

      
      


