FROM almalinux:8
RUN yum install nginx -y
ENV AUTHOR="Aadarsh" \
      INSTRUCTION="Label" \
      OS="Almalinux" 
CMD ["nginx","-g","daemon off;"]


## Developers can use this environmnet variables inside there code.
## Login to the container and run "env" we can see the ENV variabeles.


